/**:
  ros__parameters:
    voxel_size_x: 3.0
    voxel_size_y: 3.0
    voxel_size_z: 3.0
    input_frame: ""
    output_frame: ""
    max_queue_size: 5
    use_indices: false
    latched_indices: false
    approximate_sync: false
